### PR TITLE
Handling an error:

### PR DESCRIPTION
**Pull request by B0R1K**
The item '' already exists. ---> Microsoft.ReportingServices.Diagnostics.Utilities.ItemAlreadyExistsException: The item '' already exists. : System.Web.Services.Protocols.SoapException

### CODE REVIEW

**Comment by Seddryck** [comment]
Huuum, in place of catching an error you should check first if the item exists and if not create the item

**Comment by B0R1K** [comment]
Hmm, I guess I could do same thing you do for Folder(use GetItemType Method)
Thanks

**Comment by Seddryck** [comment]
Thx for the PR but I cannot merge it. The tests are failing (report parser, see above).

More than this, I have serious troubles to understand the changes. Your original work was on proposing an option to not overwrite a data source ... and now you're suggesting to add a dataSetMap (What is it, when do you need it)? Why is it i the same PR? 

A few tips:

* Avoid  to use a reformatter, it's difficult to have to review files where nothing has changed, just some spaces removed. If you want to cleanup some code files, do it in a different commit and clearly specify your intent for this commit. 
* Don't create your PR on the master branch ... create one branch by idea.
* I'd recommend to first open an issue if you want to implement a new feature and explain the goal/proposed syntax. It's easier to discuss first the design and after the actual implementation. 

Will be easier for me to accept your PR.

**Comment by B0R1K** [comment]
DataSet Name in Reports some times different then Name of SharedDataSet Define, 
instead of Defining same SharedDataSet with different name just have the Mapping...

When ShareDataSet Tag is missing an DataSource Attribute I use the Name from References 
and try to match on that. There is probably cleaner way of doing that, now that i understand most 
of the code.

Also DataSets were not being published, like i mentioned before, 
it was missing Parsers from Folder Definition.

I didn't use reformater VS added those space it self...

**Comment by B0R1K** [comment]
Also thank you for suggestion and guidance... I needed that functionality so I implemented.
I will create and Issues and we can discuss it...

**Pull request closed without merging**
